name: assemble

on:
  push:
  schedule:
    - cron: '15 01 * * SUN'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Ubuntu
      run: |
        sudo apt-get -y -q update
        sudo apt-get -y -q install haveged
        sudo systemctl enable haveged
        sudo systemctl restart haveged
    - name: Gradle Wrapper Cache
      uses: actions/cache@v1
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}
    - name: Gradle Dependencies Cache
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle') }}
    - name: Gradle Test
      run: |
        ./gradlew -Dorg.gradle.console=plain --no-daemon clean check
