name: gradle

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  schedule:
    - cron: '15 01 * * SUN'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'adopt'
    - name: Setup Ubuntu
      run: |
        sudo apt-get -y -q install haveged
        sudo systemctl enable haveged
        sudo systemctl restart haveged
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
    - name: Gradle Check
      env:
        JAVA_TOOL_OPTIONS: -Dpolyglot.js.nashorn-compat=true -Dpolyglot.engine.WarnInterpreterOnly=false
      run: |
        ./gradlew check
    - name: codecov.io
      uses: codecov/codecov-action@v3.1.0